name: nodo
on: pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: shivae372/nodo@v1.2.2
        with:
          path: '.'
          args: '--no-ast'
          comment: 'true'
